apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-stream-app
  labels:
    app: kafka-stream-app
spec:
  replicas: 1
  template:
    metadata:
      name: kafka-stream-app
      labels:
        app: kafka-stream-app
    spec:
      volumes:
        - name: jmx-config
          configMap:
            name: kafka-stream-app-jmx-configmap
      containers:
        - name: kafka-stream-app
          image: tatisled/kafka-stream-app:latest
          imagePullPolicy: Always
          env:
            - name: BOOTSTRAP_SERVERS_CONFIG
              value: "10.100.166.16:9094"
        - name: prometheus-jmx-exporter
          volumeMounts:
            - name: jmx-config
              mountPath: /etc/jmx-exporter
          image: solsson/kafka-prometheus-jmx-exporter:latest
          command:
            - java
            - -jar
            - jmx_prometheus_httpserver.jar
            - "5556"
            - /etc/jmx-exporter/jmx-prometheus.yml
          ports:
            - containerPort: 5556
              name: metrics
      restartPolicy: Always
  selector:
    matchLabels:
      app: kafka-stream-app
